# Generated by Django 5.1 on 2026-02-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klientet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('default_unit', models.CharField(choices=[('m2', 'm2'), ('ml', 'ml'), ('cope', 'cope')], default='m2', max_length=10)),
                ('default_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sherbim',
                'verbose_name_plural': 'Katalogu Sherbimeve',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('supply_work', 'Furnizim + Pune'), ('work_only', 'Vetem Pune')], default='supply_work', max_length=20)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Perfunduar'), ('cancelled', 'Anulluar')], default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.client')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projektet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Preventiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preventiv_number', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preventiv', to='core.project')),
            ],
            options={
                'verbose_name': 'Preventiv',
                'verbose_name_plural': 'Preventiva',
            },
        ),
        migrations.CreateModel(
            name='ListeCmimesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liste_cmimesh', to='core.project')),
            ],
            options={
                'verbose_name': 'Liste Cmimesh',
                'verbose_name_plural': 'Lista Cmimesh',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('materials', 'Materiale'), ('labor', 'Puntori'), ('transport', 'Transport'), ('equipment', 'Pajisje'), ('other', 'Tjeter')], default='materials', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('supplier', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.project')),
            ],
            options={
                'verbose_name': 'Kosto',
                'verbose_name_plural': 'Kostot',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PreventivItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='m2', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('preventiv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.preventiv')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecatalog')),
            ],
            options={
                'verbose_name': 'Artikull',
                'verbose_name_plural': 'Artikujt',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ListeCmimeshItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('unit', models.CharField(default='m2', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('liste_cmimesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.listecmimesh')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.servicecatalog')),
            ],
            options={
                'verbose_name': 'Artikull',
                'verbose_name_plural': 'Artikujt',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion_number', models.PositiveIntegerField(default=1)),
                ('date', models.DateField()),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('payment_status', models.CharField(choices=[('pending', 'Ne pritje'), ('paid', 'Paguar')], default='pending', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situacions', to='core.project')),
            ],
            options={
                'verbose_name': 'Situacion',
                'verbose_name_plural': 'Situacione',
                'ordering': ['situacion_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.project')),
                ('situacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.situacion')),
            ],
            options={
                'verbose_name': 'Pagese',
                'verbose_name_plural': 'Pagesat',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SituacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(default='m2', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('situacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.situacion')),
            ],
            options={
                'verbose_name': 'Artikull',
                'verbose_name_plural': 'Artikujt',
                'ordering': ['order'],
            },
        ),
    ]
